server:
  port: ${PORT}
spring:
  datasource:
    url: ${POSTGRES_URL}
    username: ${POSTGRES_USERNAME}
    password: ${POSTGRES_PASSWORD}
    platform: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop

weather:
  forecast:
    days: 3650

springdoc:
  api-docs:
    path: "/sswf-docs"